# Generated by Django 4.0.6 on 2024-04-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0003_remove_banda_festival_festival_festival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='festival',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='localizacao',
        ),
        migrations.DeleteModel(
            name='Banda',
        ),
        migrations.DeleteModel(
            name='Festival',
        ),
        migrations.DeleteModel(
            name='Localizacao',
        ),
    ]
