# Generated by Django 4.0.6 on 2024-04-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='festival',
        ),
        migrations.RemoveField(
            model_name='localizacao',
            name='festival',
        ),
        migrations.DeleteModel(
            name='Banda',
        ),
        migrations.DeleteModel(
            name='Festival',
        ),
        migrations.DeleteModel(
            name='Localizacao',
        ),
    ]
