# Generated by Django 4.0.6 on 2024-04-24 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festivais', '0006_remove_festival_festival_remove_localizacao_festival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cartaz', models.ImageField(blank=True, null=True, upload_to='media/festivais/')),
                ('festival', models.ManyToManyField(related_name='festivais', to='festivais.banda')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivais.localizacao')),
            ],
        ),
    ]
