# Generated by Django 4.0.6 on 2024-04-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandasNovas', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='musica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bandasNovas.musica'),
        ),
    ]
