# Generated by Django 4.0.6 on 2024-04-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area_Cientifica',
            new_name='Areas_Cientifica',
        ),
        migrations.RenameModel(
            old_name='Linguagem_de_Programacao',
            new_name='Linguagens_de_Programacoe',
        ),
    ]
