# Generated by Django 4.0.6 on 2024-04-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0002_rename_area_cientifica_areas_cientifica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='horas_totais',
        ),
    ]
