# Generated by Django 4.0.6 on 2024-04-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0003_remove_curso_horas_totais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='comptencias',
            new_name='competencias',
        ),
    ]
