# Generated by Django 4.0.6 on 2024-04-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0004_rename_comptencias_curso_competencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='disciplina',
        ),
        migrations.DeleteModel(
            name='Linguagens_de_Programacoe',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
