# Generated by Django 4.0.6 on 2024-04-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='area_cientifica',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='disciplinas',
        ),
        migrations.RemoveField(
            model_name='linguagens_de_programacoe',
            name='projetos',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='disciplina',
        ),
        migrations.DeleteModel(
            name='Areas_Cientifica',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Linguagens_de_Programacoe',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
