# Generated by Django 4.0.6 on 2024-05-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linguagens_de_programacoe',
            name='projetos',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tecnologias_utilizadas',
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias_utilizadas',
            field=models.ManyToManyField(to='Curso.linguagens_de_programacoe'),
        ),
    ]
