# Generated by Django 4.0.6 on 2024-06-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='artigo',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='artigo',
        ),
        migrations.DeleteModel(
            name='Artigo',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
